name: slobot
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - genesis-world
    - numpy<2

    - torch

    - https://github.com/ompl/ompl/releases/download/prerelease/ompl-1.6.0-cp312-cp312-manylinux_2_28_x86_64.whl # should match python version

    - git+https://github.com/huggingface/lerobot.git

    - gradio