name: slobot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.8
  - gcc=11.4
  - gxx=11.4
  - pip
  - pip:
    - genesis-world # git+https://github.com/Genesis-Embodied-AI/Genesis.git
    - numpy<2

    - https://github.com/ompl/ompl/releases/download/prerelease/ompl-1.6.0-cp312-cp312-manylinux_2_28_x86_64.whl

    # Uncomment to install PyTorch with ROCm support
    #- --extra-index-url https://download.pytorch.org/whl/rocm6.2.4
    #- torch==2.6.0+rocm6.2.4
    #- torchvision==0.21.0+rocm6.2.4

    - git+https://github.com/huggingface/lerobot.git